{"name": "David Agard", "email": "agard@msg.ucsf.edu", "title": "Professor", "department": " Biochemistry and Biophysics", "interests": [" Structure", " function", " and folding of proteins", " chromosomes", " and centrosomes"], "website": "http://www.msg.ucsf.edu/agard"}
{"name": "Nadav Ahituv", "email": "nadav.ahituv@ucsf.edu", "title": "Professor", "department": " Bioengineering and Therapeutic Sciences", "interests": [" Deciphering the role of gene regulatory sequences in human biology and disease"], "website": "http://bts.ucsf.edu/ahituv/"}
{"name": "Steven Altschuler", "email": "steven.altschuler@ucsf.edu", "title": "Professor", "department": " Pharmceutical Chemistry", "interests": [" Systems pharmacology and quantitative cell biology for drug discovery in cancer", " intestinal and neurodegenerative diseases"], "website": "http://www.AltschulerWuLab.org"}
{"name": "Mark Ansel", "email": "mark.ansel@ucsf.edu", "title": "Associate Professor", "department": " Microbiology & Immunology", "interests": [" Discovering and deciphering the regulatory networks that govern immunity", " with a focus on post-transcriptional mechanisms of gene regulation."], "website": ""}
{"name": "Sourav Bandyopadhyay", "email": "sourav.bandyopadhyay@ucsf.edu", "title": "Assistant Professor", "department": " Bioengineering and Therapeutic Sciences", "interests": [" Network mapping approaches to guide the development of new personalized medicines in cancer"], "website": "http://cancersignaling.net/"}
{"name": "Sergio Baranzini", "email": "sebaran@cgl.ucsf.edu", "title": "Associate Professor in Residence", "department": " Neurology", "interests": [" Genomic approaches and large-scale data integration to understand pathogenesis of complex diseases."], "website": "http://baranzinilab.ucsf.edu/"}
{"name": "Steven Brenner", "email": "brenner@compbio.berkeley.edu", "title": "Professor", "department": " Department of Plant and Microbial Biology", "interests": [" Regulation by alternative splicing", " protein function prediction", " and personal genomics"], "website": "http://compbio.berkeley.edu"}
{"name": "Atul Butte", "email": "atul.butte@ucsf.edu", "title": "Professor", "department": " Pediatrics", "interests": [" Creation and application of tools that convert more than 400 trillion points of molecular", " clinical", " and epidemiological data into diagnostics", " therapeutics", " and new insights into disease."], "website": "http://buttelab.org/"}
{"name": "Charles Chiu", "email": "charles.chiu@ucsf.edu", "title": "Assistant Prof In Res-Hcomp", "department": " Laboratory Medicine", "interests": [" Viral pathogen discovery and characterization", " computational algorithms for metagenomics analysis", " and the development and validation of next-generation sequencing-based clinical diagnostics for infectious diseases"], "website": "http://chiulab.ucsf.edu"}
{"name": "Bruce Conklin", "email": "bconklin@gladstone.ucsf.edu", "title": "Professor in residence", "department": " Gladstone Institute of Cardiovascular Disease", "interests": [" Combining the tools of molecular biology", " genetics", " bioinformatics", " and physiology to answer fundamental issues in pharmacology."], "website": "http://labs.gladstone.ucsf.edu/conklin"}
{"name": "Joe DeRisi", "email": "joe@derisilab.ucsf.edu", "title": "Professor", "department": " Biochemistry and Biophysics", "interests": [" Infectious Disease", " Genomics"], "website": "http://derisilab.ucsf.edu/"}
{"name": "Hana El-Samad", "email": "hana.el-samad@ucsf.edu", "title": "Associate Professor", "department": " Biochemistry and Biophysics", "interests": [" Computational biology/stochastic biological dynamics; modeling of biological systems"], "website": "http://biochemistry.ucsf.edu/~elsamad/"}
{"name": "Thomas Ferrin", "email": "tef@cgl.ucsf.edu", "title": "Professor", "department": " Pharmaceutical Chemistry", "interests": [" Molecular graphics; scientific visualization; computational chemistry; bioinformatics; structure-based drug design"], "website": "http://www.cgl.ucsf.edu/"}
{"name": "Kathy Giacomini", "email": "kathy.giacomini@ucsf.edu", "title": "Professor", "department": " Bioengineering and Therapeutic Sciences", "interests": [" Molecular mechanisms of nucleosides transporters and organic cations", " and pharmacogenomics"], "website": "http://bts.ucsf.edu/giacomini/"}
{"name": "Hani Goodarzi", "email": "hani.goodarzi@ucsf.edu", "title": "Assistant Professor", "department": " Biochemistry & Biophysics", "interests": [" Innovative approaches in computational and experimental cancer biology to reveal the post-transcriptional regulatory programs that drive cancer metastasis"], "website": "http://goodarzilab.ucsf.edu/"}
{"name": "Ryan Hernandez", "email": "ryan.hernandez@ucsf.edu", "title": "Associate Professor", "department": " Bioengineering and Therapeutic Sciences", "interests": [" Human population genomics", " computational and statistical inference", " and analysis of genome resequencing data."], "website": "http://bts.ucsf.edu/hernandez_lab/"}
{"name": "Jill Hollenbach", "email": "jill.hollenbach@ucsf.edu", "title": "Assistant Adjunct Professor", "department": " Neurology", "interests": [" Analysis of the extremely polymorphic human leukocyte antigen (HLA) and killer immunoglobulin-like receptor (KIR) immunogenetics systems"], "website": "https://hollenbachlab.ucsf.edu"}
{"name": "Matthew Jacobson", "email": "matt@cgl.ucsf.edu", "title": "Professor", "department": " Pharmaceutical Chemistry", "interests": [" Fundamental principles of physical chemistry and biological applications specifically modeling proteins and protein-ligand complexes using physics-based methods"], "website": "http://francisco.compbio.ucsf.edu/~jacobson/"}
{"name": "Ajay Jain", "email": "ajain@jainlab.org", "title": "Professor", "department": " Cancer Research Institute", "interests": [" Computational approaches for drug design", " molecular docking", " molecular similarity", " predictive pharmacology", " and modeling genomic and molecular phenomena involved in cancer."], "website": "http://www.jainlab.org/"}
{"name": "Alexander (Sandy) Johnson", "email": "ajohnson@cgl.ucsf.edu", "title": "Professor", "department": " Microbiology & Immunology", "interests": [" Transcription circuits", " their evolution", " and how they function in microbial pathogenesis"], "website": "http://johnsonlab.ucsf.edu/"}
{"name": "Michael Keiser", "email": "keiser@keiserlab.org", "title": "Assistant Professor", "department": " Intitute of Neurodegenerative Diseases", "interests": [" How small molecules perturb entire protein networks to achieve their therapeutic effects"], "website": "http://www.keiserlab.org"}
{"name": "Tanja Kortemme", "email": "kortemme@cgl.ucsf.edu", "title": "Professor", "department": " Bioengineering and Therapeutic Sciences", "interests": [" Computational biology", " prediction and design of protein interactions and networks", " synthetic biology"], "website": "http://kortemmelab.ucsf.edu/"}
{"name": "Nevan Krogan", "email": "nevan.krogan@ucsf.edu", "title": "Professor", "department": " Cellular and Molecular Pharmacology", "interests": [" Functional Insights from Genetic and Physical Interaction Maps"], "website": "http://kroganlab.ucsf.edu"}
{"name": "Hao Li", "email": "haoli@genome.ucsf.edu", "title": "Professor", "department": " Biochemistry and Biophysics", "interests": [" Bioinformatics", " genome sequence analysis", " gene regulation"], "website": "http://mobydick.ucsf.edu/~haoli/"}
{"name": "Wendell Lim", "email": "wendell.lim@ucsf.edu", "title": "Professor", "department": " Cellular and Molecular Pharmacology", "interests": [" Design principles of cellular signaling systems"], "website": "http://limlab.ucsf.edu/"}
{"name": "Hiten Madhani", "email": "hitenmadhani@gmail.com", "title": "Professor", "department": " Biochemistry and Biophysics", "interests": [" (1) Silencing of transposons and repeats by chromatin and RNAi; (2) fungal pathogenesis"], "website": "http://madhanilab.ucsf.edu"}
{"name": "Michael McManus", "email": "michael.mcmanus@ucsf.edu", "title": "Associate Professor", "department": " Microbiology and Immunology", "interests": [" Mammalian microRNA and RNA Interference Pathways"], "website": "http://mcmanuslab.ucsf.edu/"}
{"name": "Katie Pollard", "email": "kpollard@gladstone.ucsf.edu", "title": "Associate Professor", "department": " Gladstone Institutes", "interests": [" Evolutionary computational biology"], "website": "http://docpollard.org"}
{"name": "Neil Risch", "email": "rischn@humgen.ucsf.edu", "title": "Professor and Director", "department": " Institute for Human Genetics", "interests": [" Genetic epidemiology of complex diseases in ethnic populations"], "website": "http://humgen.medschool.ucsf.edu/"}
{"name": "Andrej Sali", "email": "sali@salilab.org", "title": "Professor", "department": " Bioengineering and Therapeutic Sciences", "interests": [" Computation grounded in the laws of physics and evolution to study the structure and function of proteins"], "website": "http://www.salilab.org/"}
{"name": "Mark Segal", "email": "mark@biostat.ucsf.edu", "title": "Professor", "department": " Epidemiology and Biostatistics", "interests": [" Genotype - phenotype association; comparing DNA fingerprints; analysis of gene expression / microarray data; statistical methods"], "website": "http://www.epibiostat.ucsf.edu/epidem/personnel/msegal2.html"}
{"name": "Mark Seielstad", "email": "mark.seielstad@ucsf.edu", "title": "Associate Professor", "department": " Institute for Human Genetics", "interests": [" Search for genetic variation underlying complex human diseases of immunity and metabolism"], "website": "http://bms.ucsf.edu/directory/faculty/mark-seielstad-phd"}
{"name": "Brian Shoichet", "email": "bshoichet@gmail.com", "title": "Professor", "department": " Pharmaceutical Chemistry", "interests": [" Molecular docking", " structure-based inhibitor discovery", " beta-lactamase activity-stability-evolution", " and crystallography."], "website": "http://shoichetlab.compbio.ucsf.edu"}
{"name": "Peter Turnbaugh", "email": "peter.turnbaugh@ucsf.edu", "title": "Assistant Professor", "department": " Microbiology & Immunology", "interests": [" Impact of the human gut microbiome on pharmacology"], "website": "http://turnbaughlab.ucsf.edu/"}
{"name": "Jeff Wall", "email": "wallj@humgen.ucsf.edu", "title": "Associate Professor", "department": " Institute for Human Genetics", "interests": [" Evolutionary and Human Genetics"], "website": "http://humgen.medschool.ucsf.edu/"}
{"name": "Leor Weinberger", "email": "leor.weinberger@gladstone.ucsf.edu", "title": "Professor", "department": " Department of Biochemistry and Biophysics", "interests": [" Single-cell imaging & mathematical modeling of fate-selection circuits"], "website": "http://weinbergerlab.ucsf.edu/"}
{"name": "Jonathan Weissman", "email": "weissman@cmp.ucsf.edu", "title": "Professor", "department": " Cellular and Molecular Pharmacology", "interests": [" Mechanism of molecular chaperones and protein folding in vivo."], "website": "http://weissmanlab.ucsf.edu/"}
{"name": "John Witte", "email": "wittej@humgen.ucsf.edu", "title": "Professor", "department": " Epidemiology & Biostatistics", "interests": [" Developing and applying statistical tools to decipher the genomic and environmental basis of complex diseases"], "website": "http://wittelab.ucsf.edu/"}
{"name": "Lani Wu", "email": "lani.wu@ucsf.edu", "title": "Professor", "department": " Pharmceutical Chemistry", "interests": [" Drug discovery", " cancer drug resistance", " neurodegeneration", " high-throughput imaging", " machine learning", " organoid models of disease."], "website": "htpp://www.AltschulerWuLab.org"}
{"name": "Jimmie Ye", "email": "jimmie.ye@ucsf.edu", "title": "Assistant Professor", "department": " Epidemiology & Biostatistics", "interests": [" Interaction between genetics and environment affect human variation at the level of molecular phenotypes"], "website": "http://yelab.ucsf.edu/"}
{"name": "Noah Zaitlen", "email": "noah.zaitlen@ucsf.edu", "title": "Assistant Professor", "department": " Medicine", "interests": [" Computational methods to discover the genetic and genomic bases of complex human phenotypes"], "website": "http://zaitlenlab.ucsf.edu"}
